<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Agenda;

use Doctrine\ORM\EntityManagerInterface;

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Verifica a existência da agenda
     * @param $params
     */
    public function validar($params) {
        $horaFinal = date('H:i', strtotime( $params['hora']->format('H:i') . ' +30 minutes'));
        $horaFinal = new \DateTime($horaFinal);

        $query = $this->createQueryBuilder('A');
        $query->where('A.data = :data')
            ->setParameter('data', $params['data']);
        $query->andWhere('A.hora = :horaInicial')
            ->setParameter('horaInicial', $params['hora']);
        $query->orWhere('A.hora = :horaFinal')
            ->setParameter('horaFinal', $horaFinal);

        return $query->getQuery()->getResult();
    }
    
    /**
     * Salva um novo agendamento
     * @param $params
     * @return boolean
     */
    public function salvar($params) {
        $agenda = new Agenda();
        $agenda->setData($params['data']);
        $agenda->setHora($params['hora']);
        $agenda->setUsuarioId($params['usuarioId']);
        
        $this->_em->persist($agenda);
        $this->_em->flush();
        
        return $agenda;
    }
    
    /**
     * Apaga um agendamento
     * @param $agenda
     * @return boolean
     */
    public function remover($agenda) {
        if ($agenda) {
            $this->_em->remove($agenda);
            $this->_em->flush();
            return true;
        } else {
            return false;
        }
    }
}
