<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Usuario;

use Doctrine\ORM\EntityManagerInterface;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Salva um novo usuario
     * @param $request
     * @return boolean
     */
    public function salvar($request) {
        $dados = $request->request->all();
        
        $usuario = new Usuario();
        $usuario->setNome($dados['nome']);
        $usuario->setUsuario($dados['usuario']);
        $usuario->setSenha($dados['senha']);
        
        $this->_em->persist($usuario);
        $this->_em->flush();
        
        return true;
    }
}
